### ISSUE TITLE
Обязательные теги для элементов

### ISSUE THREAD

**Issue by unlok** [dfilatov/bem-react#3]
Дима, привет. А почему теги [обязательны](https://github.com/dfilatov/bem-react/blob/master/lib/bemJsonToReact.js#L15) в элементах? Очень удобно было бы опускать их, как в блоках (`div`).

PS. Можно обновить `React` до `0.13.x`, вроде ничего не ломается и тесты проходят.

**Comment by dfilatov** [comment]
Good catch! fixed in 0.0.9

**Comment by unlok** [comment]
Спасибо!

**Comment by dfilatov** [comment]
React has been updated to 0.13.x in 0.0.10
